version: "3.8"

services:
  api1:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    hostname: api1
    environment:
      - PORT=8080
      - DB_HOST=mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "512MB"

  api2:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    hostname: api2
    environment:
      - PORT=8081
      - DB_HOST=mongo
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "512MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: "512MB"

  mongo:
    image: docker.io/bitnami/mongodb:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=rinha

volumes:
  localstack_data:
  mongodb_data: