### Create Transaction
POST http://localhost:9999/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1,
  "tipo" : "d",
  "descricao" : "devolve"
}

### Get Statement
GET http://localhost:9999/clientes/1/extrato
Content-Type: application/json

### Health Check
GET http://localhost:9999/health
